In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt 
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('cars.csv') 
df

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [5]:
df.sample(5)

         brand  km_driven    fuel         owner  selling_price
3913   Hyundai      16500  Petrol   First Owner         590000
3343  Mahindra     110000  Diesel   Third Owner         245000
6698    Toyota      79328  Diesel  Second Owner         750000
745       Tata     120000  Diesel   Third Owner          85000
4238     Volvo      20000  Diesel   First Owner        3800000

In [7]:
df['brand'].value_counts().nunique()

27

In [8]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [9]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

## One Hot Encoding using pandas

In [11]:
pd.get_dummies(data=df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

## K-1 OneHot Encoding

In [12]:
pd.get_dummies(data=df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

## OneHOt Encoding using Sklearn

In [14]:
df.sample(5)

        brand  km_driven    fuel         owner  selling_price
7108     Ford      35000  Diesel   First Owner         900000
2927  Hyundai      10000  Petrol   First Owner         220000
221   Renault      30000  Petrol   First Owner         335000
5263   Maruti      20000  Petrol  Second Owner         280000
2853     Fiat     185000  Diesel   Third Owner         280000

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:4],df.iloc[:,-1],random_state=42,test_size=0.2)

In [16]:
X_train.head()

        brand  km_driven    fuel                 owner
6518     Tata       2560  Petrol           First Owner
6144    Honda      80000  Petrol          Second Owner
6381  Hyundai     150000  Diesel  Fourth & Above Owner
438    Maruti     120000  Diesel          Second Owner
5939   Maruti      25000  Petrol           First Owner

In [17]:
y_train.head()

6518    520000
6144    300000
6381    380000
438     530000
5939    335000
Name: selling_price, dtype: int64

In [18]:
from sklearn.preprocessing import OneHotEncoder

In [46]:
ohe=OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

In [47]:
# X_train_ohe=ohe.fit_transform(X_train[['fuel','owner']]).toarray()
X_train_ohe=ohe.fit_transform(X_train[['fuel','owner']])

In [48]:
# X_test_ohe=ohe.transform(X_test[['fuel','owner']]).toarray
X_test_ohe=ohe.transform(X_test[['fuel','owner']])

In [49]:
X_train_ohe.shape

(6502, 7)

In [50]:
np.hstack((X_train[['brand','km_driven']],X_train_ohe)).shape

(6502, 9)

## OneHotEncoder with top categories

In [53]:
count=df['brand'].value_counts()

In [56]:
df['brand'].nunique()
threshold=100

In [57]:
repl=count[count<=threshold].index

In [58]:
pd.get_dummies(df['brand'].replace(repl,'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
174,False,False,False,False,False,False,True,False,False,False,False,False,False
3947,False,False,False,False,True,False,False,False,False,False,False,False,False
7447,False,False,False,False,False,False,False,False,False,False,False,False,True
1212,False,False,False,False,False,False,True,False,False,False,False,False,False
6763,False,False,False,False,False,False,True,False,False,False,False,False,False